"""empty message

Revision ID: 09fec18014ba
Revises: 8c5c175a2b85
Create Date: 2022-04-27 05:09:03.473728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09fec18014ba'
down_revision = '8c5c175a2b85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('propertyid', sa.Integer(), nullable=False))
    op.drop_column('properties', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('properties', 'propertyid')
    # ### end Alembic commands ###
