"""empty message

Revision ID: 8c5c175a2b85
Revises: 
Create Date: 2022-04-26 20:25:20.823474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c5c175a2b85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('rooms', sa.Integer(), nullable=False),
    sa.Column('baths', sa.Float(precision=5, asdecimal=2), nullable=False),
    sa.Column('price', sa.Float(precision=15, asdecimal=2), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('photo', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('properties')
    # ### end Alembic commands ###
